# Shell variables
# Generated by 'wal'
wallpaper='/home/ayaka/Pictures/wallpaper/uOkHaTy7_4x.jpg'

# Special
background='#190f16'
foreground='#dbd7d1'
cursor='#dbd7d1'

# Colors
color0='#190f16'
color1='#DF252D'
color2='#B35A4E'
color3='#BCA45C'
color4='#677681'
color5='#7593A3'
color6='#96A7A7'
color7='#dbd7d1'
color8='#999692'
color9='#DF252D'
color10='#B35A4E'
color11='#BCA45C'
color12='#677681'
color13='#7593A3'
color14='#96A7A7'
color15='#dbd7d1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
